spring:
  application:
    name: geo-surf-spring-boot
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
  data:
    redis:
      host: localhost
      port: 6379
springdoc:
  swagger-ui:
    path: /swagger-ui.html