spring:
  application:
    name: geo-surf-spring-boot
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    hikari:
      data-source-properties:
        ssl: true
        sslmode: verify-full
        sslrootcert: ${DB_SSL_PATH:~/.postgresql/root.crt}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html
logging:
  level:
    org:
      postgresql: DEBUG